# Generated by Django 6.0.3 on 2026-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_empresa_alter_camion_chofer_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='viaje',
            name='combustible_estimado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
