# Generated by Django 6.0.3 on 2026-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_remove_viaje_fecha_viaje_combustible_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='camion',
            name='daños',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camion',
            name='multas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viaje',
            name='daños',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viaje',
            name='multas',
            field=models.BooleanField(default=False),
        ),
    ]
