# Generated by Django 6.0.3 on 2026-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_remove_viaje_observaciones_camion_daños_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen',
        ),
        migrations.AddField(
            model_name='viaje',
            name='ciudad_destino',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='ciudad_origen',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='provincia_destino',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='provincia_origen',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
