# Generated by Django 6.0.3 on 2026-07-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_remove_viaje_destino_remove_viaje_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='camion_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje', to='flota.camion'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje', to='flota.chofer'),
        ),
    ]
