# Generated by Django 6.0.3 on 2026-07-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_alter_viaje_camion_asignado_alter_viaje_chofer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='chofer_asignado',
            new_name='chofer',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='camion_asignado',
            new_name='camion',
        ),
    ]
