# Generated by Django 6.0.3 on 2026-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_alter_viaje_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('dañado', 'Dañado')], default='activo', max_length=10),
        ),
    ]
