# Generated by Django 6.0.3 on 2026-07-19 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_alter_camion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_llegada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
