# Generated by Django 6.0.3 on 2026-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0011_alter_viaje_fecha_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
    ]
