# Generated by Django 6.0.3 on 2026-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0012_alter_viaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('inactivo', 'Inactivo'), ('dañado', 'Dañado'), ('en_viaje', 'En_viaje')], default='disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('inactivo', 'Inactivo'), ('en_viaje', 'En_viaje')], default='disponible', max_length=10),
        ),
    ]
