# Generated by Django 6.0.3 on 2026-07-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0013_alter_camion_estado_alter_chofer_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('inactivo', 'Inactivo'), ('dañado', 'Dañado'), ('en_viaje', 'En viaje')], default='disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('inactivo', 'Inactivo'), ('en_viaje', 'En viaje')], default='disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
    ]
