# Generated by Django 6.0.3 on 2026-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0014_alter_camion_estado_alter_chofer_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
    ]
