# Generated by Django 6.0.3 on 2026-07-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0015_alter_viaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camiones', to='flota.sede'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to='flota.sede'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='flota.sede'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido'), ('incidente', 'Incidente')], default='pendiente', max_length=30),
        ),
    ]
