# Generated by Django 6.0.3 on 2026-07-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0016_camion_sede_chofer_sede_viaje_sede_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='nombre',
        ),
    ]
