# Generated by Django 6.0.3 on 2026-07-28 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0017_remove_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='hora_llegada',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_salida',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
